name: xcube-geodb-openeo
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python >=3.8,<3.10
  # Required
  - click >=8.0
  - deprecated >=1.2
  - geopandas
  - pyjwt >=1.7
  - pyproj >=3.0,<3.3  # tests fail with 3.3.0, missing database on Windows
  - pyyaml >=5.4
  - requests >=2.25
  - requests-oauthlib >=1.3
  - setuptools >=41.0
  - shapely >=1.6
  - tornado >=6.0
  - flask >=2.0
  - xcube_geodb >= 1.0.2
  # Testing
  - flake8 >=3.7
  - pytest >=4.4
  - pytest-cov >=2.6
  - requests-mock >=1.8.0
