name: Unit-level tests xcube-geodb-openeo


on:
  workflow_dispatch:
  push:


env:
  APP_NAME: xcube-geodb-openeo
  ORG_NAME: bcdev

  SKIP_UNITTESTS: "0"
  WAIT_FOR_STARTUP: "1"


jobs:
  unittest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - run: |
          echo "SKIP_UNITTESTS: ${{ env.SKIP_UNITTESTS }}"
      - uses: actions/checkout@v3
        name: Checkout xcube-geodb-openeo repo
      - name: Checkout xcube repo
        uses: actions/checkout@v3
        with:
          repository: dcs4cop/xcube
          path: "xcube"
          ref: forman-676-server_redesign
      - uses: conda-incubator/setup-miniconda@v2
        if: ${{ env.SKIP_UNITTESTS == '0' }}
        with:
          mamba-version: "*"
          channels: conda-forge
          auto-update-conda: false
          activate-environment: xcube-geodb-openeo
          environment-file: environment.yml
      - run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          printenv | sort
      - name: setup-xcube
        run: |
          cd xcube
          pip install -e .
          cd ..
      - name: setup-xcube-geodb-openeo
        run: |
          pip install -e .
      - name: unittest-xcube-geodb-openeo
        if: ${{ env.SKIP_UNITTESTS == '0' }}
        run: |
          pytest --cov=./ --cov-report=xml --tb=native tests
      - uses: codecov/codecov-action@v2
        if: ${{ env.SKIP_UNITTESTS == '0' }}
        with:
          fail_ci_if_error: true
          verbose: false
